### ISSUE TITLE
FastAPI

### ISSUE THREAD

**Issue by lorivalmacedo** [lorivalmacedo/erros_em_algoritmos#1]
```cmd

(api-env) D:\CNES\saudeinteligente-api>uvicorn main:app --reload --port 8002
INFO:     Will watch for changes in these directories: ['D:\\CNES\\saudeinteligente-api']
INFO:     Uvicorn running on http://127.0.0.1:8002 (Press CTRL+C to quit)
INFO:     Started reloader process [20688] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\Loriv\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process..py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Loriv\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Loriv\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Loriv\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Loriv\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Loriv\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\CNES\saudeinteligente-api\main.py", line 7, in <module>
    from middleware.auth import AuthMiddleware
  File "D:\CNES\saudeinteligente-api\middleware\auth.py", line 4, in <module>
    from auth.service import AuthService
  File "D:\CNES\saudeinteligente-api\auth\service.py", line 6, in <module>
    from db.conectaBanco import ConectaBanco
  File "D:\CNES\saudeinteligente-api\db\conectaBanco.py", line 21, in <module>
    class ConectaBanco:
  File "D:\CNES\saudeinteligente-api\db\conectaBanco.py", line 24, in ConectaBanco
    DB_HOST = config('DB_HOST')
              ^^^^^^^^^^^^^^^^^
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CNES\saudeinteligente-api\api-env\Lib\site-packages\decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: DB_HOST not found. Declare it as envvar or define a default value.
INFO:     Stopping reloader process [20688]

(api-env) D:\CNES\saudeinteligente-api>



```

**Comment by seelaz** [comment]
Por favor verifique se o arquivo .env possui o valor DB_HOST e se vc está conectado na vpn caso esteja utilizando o banco do servidor de desenvolvimento

**Comment by seelaz** [comment]
Por favor verifique se o arquivo .env possui o valor DB_HOST e se vc está conectado na vpn caso esteja utilizando o banco do servidor de desenvolvimento
